### PR TITLE
fixed broken exit code settings during panic recovery

### LINKED ISSUE #328: After panic recovery and performing of finish steps tests are not marked as failed
### What happened?

After panic recovery and performing of finish steps tests are not marked as failed

### What did you expect to happen?

After panic I expect tests to be marked as failed ones

### How can we reproduce it (as minimally and precisely as possible)?

```golang
func TestMain(m *testing.M) {
	testEnv := env.New()
	testEnv.Setup(
		causePanic(),
	)

	os.Exit(testEnv.Run(m))
}

func causePanic() env.Func {
	return func(ctx context.Context, config *envconf.Config) (context.Context, error) {
		panic("aaaaa")

		return ctx, nil
	}
}
```
this code will cause panic and recover but exit code of `go test` command will be 0 and tests will be reported as `ok`

### Anything elese we need to know?

_No response_

### E2E Provider Used

kind

### `e2e-framework` Version

0.3.0

### OS version

any

### PR DESCRIPTION
**Pull request by harshanarayana**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Set the valid return code after recovering from a panic under the setup handlers so that the test suite is marked as failed instead of being wrongly marked as successful.

#### Which issue(s) this PR fixes:
Fixes #328

#### Special notes for your reviewer:
NA

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., Usage docs, etc.:
```docs
NONE
```

### CODE REVIEW

**Comment by vladimirvivien** [comment]
Thanks @harshanarayana for this simple but valuable contribution.

/lgtm

File: pkg/env/env.go [hunk 1]
```diff
@@ -359,6 +359,9 @@ func (e *testEnv) Run(m *testing.M) int {
 				panic(rErr)
 			}
 			klog.Errorf("Recovering from panic and running finish actions: %s, stack: %s", rErr, string(debug.Stack()))
+			// Set this exit code value to non 0 to indicate that the test suite has failed
```
Comment (vladimirvivien) [inline pkg/env/env.go:362]: 👍 Love the clear explanation here.

**Review by vladimirvivien — APPROVED** [review]
Thanks again.
