### PR TITLE
fix: CreateWithConfig handling empty image

### LINKED ISSUE #296: error when calling `envfuncs.CreateKindClusterWithConfig` with an empty image
Kind would be fine if called with an empty image (`kind create cluster --image ""`), as long as it's an empty string, resulting in the default image being used. But given that the `image` is passed as is [here](https://github.com/kubernetes-sigs/e2e-framework/blob/612165028ab40fa2e821050c8fdb2868769a27d5/support/kind/kind.go#L98), to be able to create a Kind cluster with a custom config, but the default image, we have to use a dirty hack and pass it two empty double quotes as follows:
```golang
envfuncs.CreateKindClusterWithConfig(clusterName, "\"\"", kindCfg)
```
I think `cluster.CreateWithConfig` could definitely either quote the image before passing it as an argument to `--image` or just avoid adding the flag if the image provided is an empty string.

I'd be fine with any of my suggestions above, but if erroring out on the missing image was intentional, I'd be fine also adding a dedicated function allowing to create a kind cluster with a custom config but the default image, let me know what you would prefer.

### PR DESCRIPTION
**Pull request by phisco**
Fixes #296.

### CODE REVIEW

**Review by maruina — APPROVED** [review]
LGTM

File: support/kind/kind.go [hunk 1]
```diff
@@ -95,7 +95,7 @@ func (k *Cluster) clusterExists(name string) (string, bool) {
 }
 
 func (k *Cluster) CreateWithConfig(imageName, kindConfigFile string) (string, error) {
-	return k.Create("--image", imageName, "--config", kindConfigFile)
+	return k.Create("--image", fmt.Sprintf("%q", imageName), "--config", kindConfigFile)
```
Comment (cpanato) [inline support/kind/kind.go:98]: maybe if the image is empty we remove the `--image` flag from the create instead of setting an empty string?

wdyt @vladimirvivien

Comment (phisco) [reply support/kind/kind.go:98]: Totally agree, and I would avoid quoting it then, so our hack of using `”\”\””` won’t even break. Just let me know if you want me to switch to:
```golang

func (k *Cluster) CreateWithConfig(imageName, kindConfigFile string) (string, error) {
	args := []string{"--config", kindConfigFile}
	if imageName != "" {
		args = append(args, "--image", imageName)
	}
	return k.Create(args...)
}

```

Comment (harshanarayana) [reply support/kind/kind.go:98]: +1 to what @cpanato In case if the image is an empty string, let us just drop the argument. Makes it more readable.

Comment (phisco) [reply support/kind/kind.go]: I agree, updated the PR accordingly 🙏
