### PR TITLE
GIT-112: enable framework specific fail-fast mode

### LINKED ISSUE #112: [query/bug] mark testcase as failed and stop execution when `t.FailNow()` is encountered in an assessment
[Release v0.0.5]

I have a requirement to stop the testcase execution if certain assertions during the course of the testcase fails. I thought that we could control this behaviour by using [t.FailNow](https://pkg.go.dev/testing#T.FailNow) but it just marks that assertion as `FAIL` (thus behaving as [t.Fail](https://pkg.go.dev/testing#T.Fail)) and continues execution at the next assertion/feature.

Looks like it's due to the local scope of the variable `t *testing.T` in the assertion definition. 

Is this the desired behaviour? How should I work out my requirement, workarounds or suggestions?

***

MWE:

```go
// example_test.go

package example

import (
	"context"
	"testing"

	"sigs.k8s.io/e2e-framework/pkg/envconf"
	"sigs.k8s.io/e2e-framework/pkg/features"
)

func TestExample(t *testing.T) {
	failFeature := features.New("fail-feature").
		Assess("1==2", func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
			if 1 != 2 {
				t.Log("1 != 2")
				t.FailNow() // mark test case as failed here, don't continue execution
			} else {
				t.Log("1 == 2")
			}
			return ctx
		}).
		Assess("print", func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
			t.Log("THIS LINE SHOULDN'T BE PRINTED")
			return ctx
		}).
		Feature()

	nextFeature := features.New("next-feature").
		Assess("print", func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
			t.Log("THIS LINE ALSO SHOULDN'T BE PRINTED")
			return ctx
		}).
		Feature()

	testenv.Test(t, failFeature, nextFeature)
}
```

```go
// main_test.go

package example

import (
	"log"
	"os"
	"path/filepath"
	"testing"

	"sigs.k8s.io/e2e-framework/pkg/env"
)

var testenv env.Environment

func TestMain(m *testing.M) {
	// get kubeconfig
	home, err := os.UserHomeDir()
	if err != nil {
		log.Fatal("error while getting user home directory")
	}
	testenv = env.NewWithKubeConfig(filepath.Join(home, ".kube", "config"))

	os.Exit(testenv.Run(m))
}
```

```
➜ go test . -v
=== RUN   TestExample
=== RUN   TestExample/fail-feature
=== RUN   TestExample/fail-feature/1==2
    example_test.go:15: 1 != 2
=== RUN   TestExample/fail-feature/print
    example_test.go:23: THIS LINE SHOULDN'T BE PRINTED
=== RUN   TestExample/next-feature
=== RUN   TestExample/next-feature/print
    example_test.go:30: THIS LINE ALSO SHOULDN'T BE PRINTED
--- FAIL: TestExample (0.00s)
    --- FAIL: TestExample/fail-feature (0.00s)
        --- FAIL: TestExample/fail-feature/1==2 (0.00s)
        --- PASS: TestExample/fail-feature/print (0.00s)
    --- PASS: TestExample/next-feature (0.00s)
        --- PASS: TestExample/next-feature/print (0.00s)
FAIL
FAIL    example.com     0.532s
FAIL
```

### PR DESCRIPTION
**Pull request by harshanarayana**
Closes #112 

#### Regular Mode

```bash
❯ ./example.test -test.v
=== RUN   TestExample
=== RUN   TestExample/fail-feature
=== RUN   TestExample/fail-feature/1==2
    example_test.go:15: 1 != 2
=== RUN   TestExample/fail-feature/print
    example_test.go:23: THIS LINE SHOULDN'T BE PRINTED
=== RUN   TestExample/next-feature
=== RUN   TestExample/next-feature/print
    example_test.go:30: THIS LINE ALSO SHOULDN'T BE PRINTED
--- FAIL: TestExample (0.00s)
    --- FAIL: TestExample/fail-feature (0.00s)
        --- FAIL: TestExample/fail-feature/1==2 (0.00s)
        --- PASS: TestExample/fail-feature/print (0.00s)
    --- PASS: TestExample/next-feature (0.00s)
        --- PASS: TestExample/next-feature/print (0.00s)
=== RUN   TestNext
=== RUN   TestNext/next-test-feature
=== RUN   TestNext/next-test-feature/print
    example_test.go:42: THIS LINE SHOULD BE PRINTED
--- PASS: TestNext (0.00s)
    --- PASS: TestNext/next-test-feature (0.00s)
        --- PASS: TestNext/next-test-feature/print (0.00s)
FAIL
```

#### Framework Specific `fail-fast` mode
```bash
❯ ./example.test -test.v --fail-fast
=== RUN   TestExample
=== RUN   TestExample/fail-feature
=== RUN   TestExample/fail-feature/1==2
    example_test.go:15: 1 != 2
--- FAIL: TestExample (0.00s)
    --- FAIL: TestExample/fail-feature (0.00s)
        --- FAIL: TestExample/fail-feature/1==2 (0.00s)
=== RUN   TestNext
=== RUN   TestNext/next-test-feature
=== RUN   TestNext/next-test-feature/print
    example_test.go:42: THIS LINE SHOULD BE PRINTED
--- PASS: TestNext (0.00s)
    --- PASS: TestNext/next-test-feature (0.00s)
        --- PASS: TestNext/next-test-feature/print (0.00s)
FAIL
```

### CODE REVIEW

File: pkg/env/env.go [hunk 1]
```diff
@@ -441,13 +445,22 @@ func (e *testEnv) execFeature(ctx context.Context, t *testing.T, featName string
 				}
 				ctx = assess.Func()(ctx, t, e.cfg)
 			})
+
+			if e.cfg.FailFast() && t.Failed() {
```
Comment (vladimirvivien) [inline pkg/env/env.go:449]: Since `t.Failed()` is checked, is this feature dependent on test writer calling `t.FailNow()` (or similar)? If so, it should be stated in the README.md that the test writer must signal failure.

File: pkg/env/env.go [hunk 2]
```diff
@@ -441,13 +445,22 @@ func (e *testEnv) execFeature(ctx context.Context, t *testing.T, featName string
...
+			}
 		}
 
 		// teardowns run at feature-level
 		teardowns := features.GetStepsByLevel(f.Steps(), types.LevelTeardown)
 		for _, teardown := range teardowns {
 			ctx = teardown.Func()(ctx, t, e.cfg)
 		}
+
+		if e.cfg.FailFast() && failed {
```
Comment (vladimirvivien) [inline pkg/env/env.go:461]: Should this happen before teardown ?
This issue, #98, seems to want to skip all subsequent steps, including teardown, when fail-fast is signaled.

**Review by vladimirvivien — COMMENTED** [review]
This is a great start @harshanarayana Thanks for the effort.
I left some comments.

File: examples/fail_fast/README.md [hunk 3]
```diff
@@ -0,0 +1,120 @@
+# Fail Fast Mode
+
+There are times in your test infra that you want the rest of your feature assessments to fail in
+case if one of the current executing assessments fail.
+This can aid in getting a better turn around time especially in cases where you assessments are
```
[the remark this answers is not in the document]
Comment (harshanarayana) [reply examples/fail_fast/README.md:5]: Done

File: pkg/env/env.go (hunk 1 above)
Comment (harshanarayana) [reply pkg/env/env.go:449]: Yes. Right now the decision of if things are to fail or not is upto the test writer. With the flag enabled, they can terminate the workflow where they see fit. This way, we need not infer and make decision for them and the writers can do it themselves. I will update the document here as well + the Readme too.

File: pkg/env/env.go (hunk 2 above)
Comment (harshanarayana) [reply pkg/env/env.go:461]: Makes sense. I think this Issue totally skipped my mind when I wrote this. Moving this above the teardown makes sense.

**Comment by harshanarayana** [comment]
@vladimirvivien  sorry for the delay once again. Here is an updated commit with the necessary changes you have requested.

**Comment by vladimirvivien** [comment]
@harshanarayana no need to apologize. I understand.
I will take a look.

File: examples/fail_fast/README.md [hunk 4]
```diff
@@ -0,0 +1,132 @@
...
+		}).
+		Feature()
+
+	testenv.Test(t, nextFeature)
+}
+```
+
+When run this using `--fail-fast` you get the following behavior.
+
+```bash
```
Comment (vladimirvivien) [inline examples/fail_fast/README.md:116]: Please show the full `go test` command.

File: pkg/flags/flags.go [hunk 5]
```diff
@@ -75,6 +76,10 @@ var (
 		Name:  flagParallelTestsName,
 		Usage: "Run test features in parallel",
 	}
+	failFastFlag = flag.Flag{
+		Name:  flagFailFast,
+		Usage: "Fail the feature and rest of the features of the test on any test failure",
```
Comment (vladimirvivien) [inline pkg/flags/flags.go:81]: I think this may need to be reworded.
`Fail immediately and stop running untested code` or something similar.

**Review by vladimirvivien — COMMENTED** [review]
This looks great @harshanarayana 
I left a couple of comments.

File: examples/fail_fast/README.md (hunk 4 above)
Comment (harshanarayana) [reply examples/fail_fast/README.md:116]: Done

File: pkg/flags/flags.go (hunk 5 above)
Comment (harshanarayana) [reply pkg/flags/flags.go]: Done.

**Comment by harshanarayana** [comment]
@vladimirvivien  addressed the review comments. PTAL when you can.

**Review by vladimirvivien — APPROVED** [review]

**Comment by harshanarayana** [comment]
@vladimirvivien  Had to rebase the changes. PTAL and help me with an Approve + LGTM please.

**Review by vladimirvivien — APPROVED** [review]
LGTM

My bad, I should have had you rebased before lgtm last time.
