### PR TITLE
After setup error, do klog.Error not klog.Fatal, and move on

### LINKED ISSUE #188: Gracefully exit when setup fail
https://github.com/kubernetes-sigs/e2e-framework/blob/d19e8b569fb2f94568f8ed74b00227f879798aa0/pkg/env/env.go#L369

Due to the usage of `klog.Fatalf()`, it calls internally `os.Exit()`, and we can't gracefully run the clean ups.

### PR DESCRIPTION
**Pull request by codegold79**
When an error happens during a setup step, instead of calling `klog.Fatal` which causes `os.Exit`, instead do `klog.Error`, `break`, run `defer` function with clean up steps, and `return`.

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
I found [this line](https://github.com/kubernetes-sigs/e2e-framework/blob/d19e8b569fb2f94568f8ed74b00227f879798aa0/pkg/env/env.go#L369) to be the problem as to why our KinD cluster deletion was not happening as intended. As soon as an error value is passed during a setup step, `klog.Fatalf(...)` is called:

```go
for _, setup := range setups {
    // context passed down to each setup
    if e.ctx, err = setup.run(e.ctx, e.cfg); err != nil {
        klog.Fatalf("%s failure: %s", setup.role, err)
   }
}
```

According to [klog docs](https://github.com/kubernetes/klog/blob/6ded8085b27eeaf68a13d583a382b125ef1482ee/klog.go#L1606-L1607),

> // Fatal logs to the FATAL, ERROR, WARNING, and INFO logs,
> // prints stack trace(s), then calls OsExit(255).

To reiterate, `klog.Fatal` is stopping all operations and exiting program with `os.Exit`. This is not the behavior I want. What I want to happen is for the setup range loop to stop trying to do the setup steps, and try to get to the function return, `return m.Run()`. However, before returning, I expect the defer block to run next where the finishing steps, like cluster cleanup, happen.

#### Which issue(s) this PR fixes:

Fixes #188 

#### Does this PR introduce a user-facing change?

```release-note
Gracefully exit when setup fails
```

#### Additional documentation e.g., Usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by codegold79** [comment]
I'm thinking about how to write a test that ensures finish/clean up steps happen after setup step fails. This PR will be a WIP until I can get some tests up.

**Review by neolit123 — COMMENTED** [review]
/ok-to-test

File: examples/graceful_setup_fail/main_test.go [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+
+	"k8s.io/klog/v2"
+	"sigs.k8s.io/e2e-framework/pkg/env"
+	"sigs.k8s.io/e2e-framework/pkg/envconf"
+	"sigs.k8s.io/e2e-framework/pkg/features"
+)
+
+var testEnv env.Environment
+
+func TestMain(m *testing.M) {
```
Comment (vladimirvivien) [inline examples/graceful_setup_fail/main_test.go:33]: Hi @codegold79 
TestMain is usually reserved for setting up test resources, not running tests itself.

You probably can make your test simpler by moving your test environment into a proper TestXXX function.
There is nothing special about the testEnv variable, you can declare within a test and add step to it with no problem.

Check out these tests here - https://github.com/kubernetes-sigs/e2e-framework/blob/main/pkg/env/env_test.go

File: examples/graceful_setup_fail/main_test.go [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+	"strings"
+	"testing"
+
+	"k8s.io/klog/v2"
+	"sigs.k8s.io/e2e-framework/pkg/env"
+	"sigs.k8s.io/e2e-framework/pkg/envconf"
+	"sigs.k8s.io/e2e-framework/pkg/features"
+)
+
+var testEnv env.Environment
```
Comment (vladimirvivien) [inline examples/graceful_setup_fail/main_test.go:31]: Also, if you are going to test the construction of testEnv, you may not want it to be global. Just create a new one as needed.

**Review by vladimirvivien — COMMENTED** [review]
HI @codegold79 thanks for taking on this. This is a good start, I left some comments about the structure of your test.

File: examples/graceful_setup_fail/main_test.go (hunk 1 above)
Comment (codegold79) [reply examples/graceful_setup_fail/main_test.go:33]: Thanks @vladimirvivien for taking the time to review and provide feedback.
> TestMain is usually reserved for setting up test resources, not running tests itself...
> You probably can make your test simpler by moving your test environment into a proper TestXXX function.

I might be missing or misunderstanding something, but I wasn't able to figure out how to put the tests into a TestXXX function. At first, I tried to add a test to `func TestEnv_APIMethods(t *testing.T)` at https://github.com/kubernetes-sigs/e2e-framework/blob/332536f9ed7ed22fd069c5622b057a91ceeb1208/pkg/env/env_test.go#L46C6-L46C24. I also tried to add a test to `func TestEnv_Test(t *testing.T)` at https://github.com/kubernetes-sigs/e2e-framework/blob/332536f9ed7ed22fd069c5622b057a91ceeb1208/pkg/env/env_test.go#L137C1-L137C32.

With both TestXXX functions, I had the same problem: the [defer block](https://github.com/kubernetes-sigs/e2e-framework/blob/332536f9ed7ed22fd069c5622b057a91ceeb1208/pkg/env/env.go#L353-L377) is not reached in `func (e *testEnv) Run(m *testing.M) (exitCode int)` at https://github.com/kubernetes-sigs/e2e-framework/blob/332536f9ed7ed22fd069c5622b057a91ceeb1208/pkg/env/env.go#L345C1-L345C52.

I believe to reach that block, my only option is to call `func (e *testEnv) Run(m *testing.M) (exitCode int)`. But that funciton requires passing in `m *testing.M`. And the only way I know to pass that variable in is via `TestMain(...)`. Hench why I added an example package to do the testing, as all the examples use TestMain(...).

The reason why I believe that[defer block](https://github.com/kubernetes-sigs/e2e-framework/blob/332536f9ed7ed22fd069c5622b057a91ceeb1208/pkg/env/env.go#L353-L377) needs to be called is that's where the finish steps are run in case an error happens during a setup step.

I hope despite my lack of brevity, I was able to show my limited understanding, and perhaps you or another person might help me figure out a better way to do the testing.

File: examples/graceful_setup_fail/main_test.go (hunk 2 above)
Comment (codegold79) [reply examples/graceful_setup_fail/main_test.go:31]: Will do!

**Comment by vladimirvivien** [comment]
@codegold79 apologies for the delay.
let me know if this ready for another round of review.

**Comment by codegold79** [comment]
Thanks, @vladimirvivien! I responded to your first review comment and tried to explain why I had to make a separate example and use `TestMain`. 

As for your second review comment, I made the change as you suggested. I also got rid of the dummy test. as it doesn't help anything except to not trigger a warning that there are no tests. The thing is, I'm not testing any features, I'm making sure the final actions complete even after a panic in the setup, before any feature tests happen.

PR is ready for review again.

**Comment by vladimirvivien** [comment]
@codegold79 (apologies for the late reply)
I did spend sometimes to see if this can be tested using a normal test function and I think you are doing the right thing.

/lgtm

**Comment by vladimirvivien** [comment]
Hi @codegold79 can you please squash commits. Thanks.

**Review by cpanato — APPROVED** [review]
thanks
/lgtm
